### ISSUE TITLE
Upgrade jfrog-cli-core & jfrog-client-go 

### ISSUE THREAD

**Issue by eyalbe4** [eldada/metrics-viewer#4]
It is recommended to upgrade the jfrog-cli-core and jfrog-client-go depedencies used by this plugin to their latest versions, to receive code upgrades and fixes, and then publish a new release to their plugins registry.

**Comment by eldada** [comment]
@yinonavraham , @noamshemesh - can you guys give us a hand here?
Need to replace 
```
	github.com/jfrog/jfrog-cli-core v0.0.1
	github.com/jfrog/jfrog-client-go v0.16.0
```
with
```
	github.com/jfrog/jfrog-cli-core/v2 v2.3.0
	github.com/jfrog/jfrog-client-go v1.4.0
```

Notice the `v2`.
There is also some code refactoring to do that I want your review.

If you take it, please make sure we are in sync.
Once we have a new version ready, I'll publish it to the plugins registry.

**Comment by yinonavraham** [comment]
@eldada @noamshemesh I'm looking into it.

**Comment by eldada** [comment]
@yinonavraham - consider updating other dependencies while at it...
